"""initial schema

Revision ID: 9cf285aae544
Revises: 
Create Date: 2026-05-04 18:02:48.412887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf285aae544'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('vector_index', sa.String(length=255), nullable=True),
    sa.Column('document_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_id'), 'chat_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_is_draft'), 'chat_conversations', ['is_draft'], unique=False)
    op.create_index(op.f('ix_chat_conversations_org_id'), 'chat_conversations', ['org_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_vector_index'), 'chat_conversations', ['vector_index'], unique=False)
    op.create_table('chat_conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('reasoning_content', sa.Text(), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversation_messages_conversation_id'), 'chat_conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_conversation_messages_id'), 'chat_conversation_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_conversation_messages_id'), table_name='chat_conversation_messages')
    op.drop_index(op.f('ix_chat_conversation_messages_conversation_id'), table_name='chat_conversation_messages')
    op.drop_table('chat_conversation_messages')
    op.drop_index(op.f('ix_chat_conversations_vector_index'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_org_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_is_draft'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
